# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a3a1a0f56f3680067bea7822d1db53a9b6a9b64fd429e4fe6298fe89a48963f861bef7c9be10dd9bfa850ac08e68f55094929b9934425ac9a2ceebe59d31b51

test:
  secret_key_base: 6a17abf4ff362f8b0705a001c9ac0413b50d61d8e941f3a46e5d4d04ba3dd35f913bb6e245db4901256a20c9a7127c555a1bf02039b69db6fb5191d69e840bf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
